# Generated by Django 4.1.3 on 2022-11-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('floor', models.IntegerField(default=0)),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('CO2', models.IntegerField()),
                ('ventilation', models.IntegerField()),
                ('comfortable', models.BooleanField(default='', max_length=70)),
                ('facility_outlet', models.IntegerField()),
                ('facility_noise', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Rooms',
                'db_table': 'Rooms',
            },
        ),
    ]
